### ISSUE TITLE
[Feature request] Custom colors

### ISSUE THREAD

**Issue by ThatOneCalculator** [discord-extensions/modern-indicators#1]

**Comment by LuckFire** [comment]
Can you elaborate on this a bit more? As you are able to already define custom colors for everything.

**Comment by ThatOneCalculator** [comment]
Some themes in GooseMod have the ability to change the colors in a menu instead of editing the theme manually, shouldve been more specific about that

**Comment by LuckFire** [comment]
> Some themes in GooseMod have the ability to change the colors in a menu instead of editing the theme manually, shouldve been more specific about that

I'm not too sure how I'd be the one to enable the ability to allow that though, any clue how?
