### ISSUE TITLE
Update BD "Direct Download" link

### ISSUE THREAD

**Issue by literon36** [discord-extensions/modern-indicators#10]
I just realized my .CSS is outdated by two patch versions but trying to download a newer version via the README just links to the no longer existent releases...

Also tried using [./clients/modern-indicators.theme.css](https://github.com/discord-extensions/modern-indicators/blob/main/clients/modern-indicators.theme.css) but BD just spits out the "META not found" error.

On a side note, please consider adding an `@updateUrl` which could make things a lot easier in the future :)

**Comment by LuckFire** [comment]
Thank you for reminding me -- I'll make sure to update the link soon!
Also, appreciate the tip. I wasn't aware that the BD meta had an `@updateUrl` tag to it, will add that as well.
Edit: accidentally mentioned someone

**Comment by LuckFire** [comment]
This is referring to the [addon documentation](https://docs.betterdiscord.app/developers/addons#meta) but, it doesn't seem like `@updateUrl` exists in the meta natively? Is this something for a plugin that automatically updates BD themes?

I'm going to assume the documentation is somewhat out of date regarding this.

**Comment by LuckFire** [comment]
Updated by adding a [new release](https://github.com/discord-extensions/modern-indicators/releases/tag/betterdiscord) -- should be properly downloadable now.

**Comment by literon36** [comment]
Edit: I'm an idiot; you already added the updateUrl lol

Edit 2: Apparently I just suffered a BD moment, the META error just randomly vanished!?!?

thanks for fixing :)))
