### ISSUE TITLE
[Feature request] Change priority of states & border settings

### ISSUE THREAD

**Issue by Biiox** [discord-extensions/modern-indicators#2]
When selecting the voice channel you're connected to the `selected/blue` color takes priority over the `connected/green`,  would it be possible to make the connected voice channel always take priority? 

![Example](https://i.imgur.com/xkPMaB2.gif)

And is it possible to have an individual border size setting for each state or have the border not share color/alpha with the channel icon (speaker or hashtag)?

For example right now if I'd like to remove the bar just from the unread indicator but not make the channel icon disappear I don't think I can.

Also what does indicator rounding used for?

**Comment by LuckFire** [comment]
> would it be possible to make the connected voice channel always take priority?

Sadly not, as Discord completely replaces the `modeConnected` class with the `modeSelected` one.

> And is it possible to have an individual border size setting for each state or have the border not share color/alpha with the channel icon (speaker or hashtag)?

It would be tedious and very unnecessary to do that for the actual theme, however you could easily add something into your QuickCSS that allows you to do border sizing for specific ones. If you'd like the icons to not share the color with the border, you can change the icons variable color for the indicator (for example, `--indicator-selected-icons`).

> Also what does indicator rounding used for?

It allows you to add rounding to the indicators. For example, `--indicator-rounding-info: 0 25px 25px 0;` would look like this:
![image](https://user-images.githubusercontent.com/39076891/151261322-ced3988a-8d8f-4127-b118-55afd7207ea0.png)


Also, I apologize for the late reply.
