### ISSUE TITLE
Theme Not Working [BETTERDISCORD]

### ISSUE THREAD

**Issue by theblueplum** [discord-extensions/modern-indicators#3]
Read the title basically. The theme is on and it does nothing. I'm using BetterDiscord to load it.

![image](https://user-images.githubusercontent.com/62518497/162844708-c4a828a3-79e9-449d-a551-477085e1a691.png)
![image](https://user-images.githubusercontent.com/62518497/162844736-1e766763-205c-4e81-a2c6-6474d56a12e6.png)

**Comment by LuckFire** [comment]
You'll have to redownload the theme. It appears the BetterDiscord website page won't automatically update where to download the source from either, so I'll do something about that later.

To redownload, [go here](https://raw.githubusercontent.com/discord-extensions/modern-indicators/main/support/modern-indicators.theme.css), press CTRL + S, and put the file into your themes folder.

**Comment by theblueplum** [comment]
Yeah it appears to be working now. Thanks for the help
