### ISSUE TITLE
add support for vencord

### ISSUE THREAD

**Issue by Spelis123** [discord-extensions/modern-indicators#8]
add support for vencord

**Comment by idntknwlouis** [comment]
yeah, they should

**Comment by ghost** [comment]
Support should work when copying over the raw CSS file link below or go to `src/source.css`, press raw at the top and copy that link:
`https://raw.githubusercontent.com/discord-extensions/modern-indicators/main/src/source.css`

**Comment by LuckFire** [comment]
It's better to use `https://discord-extensions.github.io/modern-indicators/src/source.css` as your import link, it loads it relatively faster (unless I'm out of practice and github made that load faster lol).

Anyways, it is now mentioned in the README!
https://github.com/discord-extensions/modern-indicators#-vencord
